### ISSUE TITLE
Do you have the codes to obtain rotational poses using blender rigid body simulation?

### ISSUE THREAD

**Issue by ankanbhunia** [rehg-lab/LSME#1]
As the title says can you provide the relevant codes for the same?

**Comment by ngailapdi** [comment]
Hi @ankanbhunia 

Thank you for your interest in our work. We will update the code with this script in the next few days and will notify you.

**Comment by ngailapdi** [comment]
Hi @ankanbhunia 
The code for sampling object poses is [here](https://github.com/rehg-lab/LSME/tree/main/data_generation/object_pose_sampling). Please check it out and let me know if you have any question.
